rules:
  - description: EmoOcto API route
    routes:
      - match:
          prefix: /api/emoocto-api/healthz
        action:
          prefixRewrite: /healthz
      - match:
          prefix: /api/emoocto-api/pet/interact
        action:
          prefixRewrite: /pet/interact
      - match:
          prefix: /api/emoocto-api/pet/state
        action:
          prefixRewrite: /pet/state
    targets:
      - containerApp: emoocto-api

  - description: BouncyBun API route
    routes:
      - match:
          prefix: /api/bouncybun-api/healthz
        action:
          prefixRewrite: /healthz
      - match:
          prefix: /api/bouncybun-api/pet/interact
        action:
          prefixRewrite: /pet/interact
      - match:
          prefix: /api/bouncybun-api/pet/state
        action:
          prefixRewrite: /pet/state
    targets:
      - containerApp: bouncy-bun

  - description: ChillTurtle API route
    routes:
      - match:
          prefix: /api/chillturtle-api/healthz
        action:
          prefixRewrite: /healthz
      - match:
          prefix: /api/chillturtle-api/pet/interact
        action:
          prefixRewrite: /pet/interact
      - match:
          prefix: /api/chillturtle-api/pet/state
        action:
          prefixRewrite: /pet/state
    targets:
      - containerApp: chillturtle-api

  - description: ChaosDragon API route
    routes:
      - match:
          prefix: /api/chaosdragon-api/healthz
        action:
          prefixRewrite: /healthz
      - match:
          prefix: /api/chaosdragon-api/pet/interact
        action:
          prefixRewrite: /pet/interact
      - match:
          prefix: /api/chaosdragon-api/pet/state
        action:
          prefixRewrite: /pet/state
    targets:
      - containerApp: chaosdragon-api

  - description: BabyDino API route
    routes:
      - match:
          prefix: /api/babydino-api/healthz
        action:
          prefixRewrite: /healthz
      - match:
          prefix: /api/babydino-api/pet/interact
        action:
          prefixRewrite: /pet/interact
      - match:
          prefix: /api/babydino-api/pet/state
        action:
          prefixRewrite: /pet/state
    targets:
      - containerApp: babydino-api