rules:
  - description: EmoOcto API route
    routes:
      - match:
          prefix: /api/octo/healthz
        action:
          prefixRewrite: /healthz
      - match:
          prefix: api/octo/pet/interact
        action:
          prefixRewrite: /pet/interact
      - match:
          prefix: api/octo/pet/state
        action:
          prefixRewrite: /pet/state
    targets:
      - containerApp: emoocto-api

  - description: BouncyBun API route
    routes:
      - match:
          prefix: /api/bunny/healthz
        action:
          prefixRewrite: /healthz
      - match:
          prefix: api/bunny/pet/interact
        action:
          prefixRewrite: /pet/interact
      - match:
          prefix: api/bunny/pet/state
        action:
          prefixRewrite: /pet/state
    targets:
      - containerApp: bouncy-bun

  - description: ChillTurtle API route
    routes:
      - match:
          prefix: /api/turtle/healthz
        action:
          prefixRewrite: /healthz
      - match:
          prefix: api/turtle/pet/interact
        action:
          prefixRewrite: /pet/interact
      - match:
          prefix: api/turtle/pet/state
        action:
          prefixRewrite: /pet/state
    targets:
      - containerApp: chillturtle-api

  - description: ChaosDragon API route
    routes:
      - match:
          prefix: /api/dragon/healthz
        action:
          prefixRewrite: /healthz
      - match:
          prefix: api/dragon/pet/interact
        action:
          prefixRewrite: /pet/interact
      - match:
          prefix: api/dragon/pet/state
        action:
          prefixRewrite: /pet/state
    targets:
      - containerApp: chaosdragon-api

  - description: BabyDino API route
    routes:
      - match:
          prefix: /api/dino/healthz
        action:
          prefixRewrite: /healthz
      - match:
          prefix: api/dino/pet/interact
        action:
          prefixRewrite: /pet/interact
      - match:
          prefix: api/dino/pet/state
        action:
          prefixRewrite: /pet/state
    targets:
      - containerApp: babydino-api